### PR TITLE
support Russian characters

### PR DESCRIPTION
**Pull request by Igorello74**
Support Russian characters to be translated to Morse, so that one can use Russian words in their wordlists.

### CODE REVIEW

**Comment by Igorello74** [comment]
@cniesen, what's wrong, why are you ignoring me?

**Comment by cniesen** [comment]
@Igorello74 Thanks for the PR I'll take a look at it this week and try to make a new release.

**Comment by Igorello74** [comment]
@cniesen thank you, get it

**Comment by cniesen** [comment]
@Igorello74 I refactored the code a bit and added prosign support as well.  
Since I don't have Russian on my phone I can't test the app totally (i.e. text-to-speech is totally quiet for me with the Russian characters).  Can you verify that it works? The apk is at https://github.com/cniesen/morsetrainer/releases/tag/4.2 and a beta should be available in the PlayStore soon. Thanks.

**Comment by Igorello74** [comment]
I don't know, there is something wrong with the speech-sythesis, Morse generating works fine, though. Firstly, I just started the app with Russian words, no synthesis worked. Then I intentionally set it to force Russian language, but it didn't help.

**Comment by cniesen** [comment]
I totally missed the [text-to-speech locale setting](https://github.com/cniesen/morsetrainer/blob/3d31b3ed5e780782353dba3d96aa09b869b9c2ce/app/src/main/java/com/niesens/morsetrainer/TextSpeaker.java#L48). It needs to switch to Russian there.

I guess depending on the word list, you'd want to hear English or Russian. Seems like an in app option to switch locales doesn't make as much sense.  Adding a locale indicator to the world list file seems to be better.
I'm thinking about an optional first line that specifies the language.  If it doesn't exist then the app will default to English.

**Comment by Igorello74** [comment]
Sounds well.I'm not good at this, but I think you could try not to set any locale setting at all. I believe that it would use the language specified in the TTS-engine settings, thus not bothering the user with the locale line. Regards.

**Comment by cniesen** [comment]
I've updated the app.  It now uses the device's locale (language) unless the word file explicitly specifies a language.  Meaning if your phone is using Russian, the Russian word file works fine, however the provided English probably won't. 
To fix that you'd need to add `OPTIONS: speech-language=en` as the first line of the word file.

If your phone is in English then you'd need to add `OPTIONS: speech-language=ru` to the Russian word files.

I've updated the release here but not the beta on google play. Let me know if that works for you.

**Comment by Igorello74** [comment]
Now it works fine, except it won't speak anything but Russian. I started the abc.txt and heard English letters spoken by a Russian synthesizer. Then, I added the language setting line, but no difference. Then, I went to the Android TTS settings and forced it to English (US), but no use again. It's rather strange why it speaks Russian — I set English everywhere but the Region.

I've got a few things to say:

* you should better check the TTS-engine's language setting, rather than the device's one;

* I can't find those files (in the repo), but it would be great if there had been forced language settings in abc.txt and so on;

* there should be some help about the locale-line.BTW, if the app works with multiple languages, it should have translations. Can you please tell me how to write one (I can't find files to translate)?

Thanks.

**Comment by cniesen** [comment]
I fixed a small issue.  Using the android studio emulator, running a phone in Russian and playing English word lists works for me.  Maybe you can try again.

As for the app translation, you'd need to translate the "app/src/main/res/values-ru/" files.

**Comment by Igorello74** [comment]
@cniesen sorry for the long wait, been busy studying (I'm a school student). I've checked the last release, it works really nice, thanks!
Gonna do the translation soon (promise)

**Pull request closed without merging**
